[custom]
; ACL4SSR 极简版（无国家分组 / 无自动选择 / 无手动切换）

; ========== 规则 ==========
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🚀 节点选择,[]FINAL

; ========== 代理组 ==========
custom_proxy_group=🚀 节点选择`select`.*

custom_proxy_group=🎯 全球直连`select`[]DIRECT
custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT

enable_rule_generator=true
overwrite_original_rules=true
